### ISSUE TITLE
Error: Every reporter object must have an init method

### ISSUE THREAD

**Issue by Lukars** [hapijs/good-console#46]
Hi, I am currently learning to use hapi - I want to use good-console to create some kind of site analytics. I end up with the above error, see my repo ( server.js) https://github.com/lajj/picup/tree/problemwithgood

This is the entire error message from my terminal:
```
/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/good/node_modules/hoek/lib/index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Every reporter object must have an init method
    at Object.exports.assert (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/good/node_modules/hoek/lib/index.js:723:11)
    at /Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/good/lib/monitor.js:148:14
    at iterate (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/good/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/good/node_modules/items/lib/index.js:38:9)
    at internals.Monitor.start (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/good/lib/monitor.js:124:11)
    at Object.exports.register (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/good/lib/index.js:17:20)
    at /Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/hapi/lib/plugin.js:254:14
    at iterate (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/hapi/node_modules/items/lib/index.js:38:9)
    at internals.Plugin.register (/Users/lukars/Desktop/FoundersCoders/makemehapi/picup/node_modules/hapi/lib/plugin.js:236:11)
18 Jun 16:37:57 - [nodemon] app crashed - waiting for file changes before starting...```

**Comment by arb** [comment]
You have a version mismatch between good and one of the reporter objects. Try removing all your node modules and reinstalling them. Also looking at your package.json to the branch you linked me, you aren't even using good-console.

**Comment by arb** [comment]
Also, please see this identical issue: https://github.com/hapijs/good-console/issues/39

**Comment by Lukars** [comment]
Thanks for the quick reply! I have read the issue, and i did follow these instructions. On my machine I also did install the latest versions of good/good-console/good-file, but forgot to put good-console into the package.json. i must have missed installing good-console globally, thank you very much!

**Comment by arb** [comment]
You really shouldn't be installing any of those packages globally, but as long as your issue is resolved, that's fine.
