### ISSUE TITLE
Error: Every reporter object must have an init method 

### ISSUE THREAD

**Issue by juliosmelo** [hapijs/good-console#69]
I try to use good 6.0.0 and good-console 6.0.0. I'm currtently using node 4.4.2 and hapijs 13.3.0
Error from terminal
Error: Every reporter object must have an init method
    at Object.exports.assert (/Users/juliomelo/Projects/findtruck/rest/node_modules/good/node_modules/hoek/lib/index.js:731:11)
    at /Users/juliomelo/Projects/findtruck/rest/node_modules/good/lib/monitor.js:147:14
    at iterate (/Users/juliomelo/Projects/findtruck/rest/node_modules/good/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/juliomelo/Projects/findtruck/rest/node_modules/good/node_modules/items/lib/index.js:38:9)
    at internals.Monitor.start (/Users/juliomelo/Projects/findtruck/rest/node_modules/good/lib/monitor.js:123:11)
    at Object.exports.register (/Users/juliomelo/Projects/findtruck/rest/node_modules/good/lib/index.js:17:20)
    at Object.target [as register] (/Users/juliomelo/Projects/findtruck/rest/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/Users/juliomelo/Projects/findtruck/rest/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/Users/juliomelo/Projects/findtruck/rest/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/juliomelo/Projects/findtruck/rest/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Plugin.parent.auth.internals.Plugin.register.each [as register] (/Users/juliomelo/Projects/findtruck/rest/node_modules/hapi/lib/plugin.js:320:11)
    at setup (/Users/juliomelo/Projects/findtruck/rest/server.js:26:9)
    at Object.<anonymous> (/Users/juliomelo/Projects/findtruck/rest/server.js:44:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by arb** [comment]
6.0.0 is not ready to be used with good yet. If you do `npm install good-console` you should be getting version 5.3.1, not 6.0.0. That is the version compatible with good 6.
